### ISSUE TITLE
Electron not running, sending message without signature data

### ISSUE THREAD

**Issue by michaelphagen** [mautrix/gvoice#7]
As with #4 , I am unable to send any messages using this bridge. I see in the logs "Electron not running, sending message without signature data".

I am running the bridge as a docker container, if that is relevant.

**Comment by tulir** [comment]
Electron is required for non-workspace accounts

**Comment by michaelphagen** [comment]
So this bridge only supports workspace accounts? That should be indicated in the documentation if so, I'm happy to make the update and PR, just confirm that is the case.

**Comment by tulir** [comment]
The bridge supports normal accounts as long as electron is available

**Comment by michaelphagen** [comment]
And electron is not available in the docker configuration documented on the main page, I surmise?

**Comment by chaoticbear** [comment]
I am using a workspace account and after a few days of being logged in I get a similar error as above when sending (I can still receive) 

Since this is marked `not planned`, I am considering making a fork with docker running in electron, other than making electron available in the image is there any specific config the app needs to know how to access electron? 

Secondarily is electron going to need to show an actual GUI window to the user with a captcha or something like that? Or does it just need to run a browser instance to connect to google voice.

**Comment by clari7744** [comment]
So this is a permanent bork, then? hmm
Would it be possible to change the error message to say "This bridge doesn't work on web" or something of the like, so that it doesn't just seem completely broken? When I see 429 I think "ratelimit", not "electron needed and the browser version doesn't have it" (although it does say `electron status: unavailable`, I don't really know what that means.)
![Too Many Requests](https://http.cat/429)

**Comment by tulir** [comment]
Nothing to do with browsers, the Matrix client you use is irrelevant. The bridge needs access to the `electron` binary, which it will run in headless mode and execute some javascript inside. Even in headless mode, electron requires a lot of dependencies, which is why it's not included in the docker image. It's much easier to just run the bridge and electron outside docker

**Comment by chaoticbear** [comment]
@tulir easier, yes. I still prefer some isolation from the host OS and other containers on my server. 

If I submit a PR with a separate `Dockerfile.electron` would you consider merging it so that folks who prefer the light isolation of docker containers can build & use it?

**Comment by tulir** [comment]
Sure
